### ISSUE TITLE
Inconsistent formatting of numeric values.

### ISSUE THREAD

**Issue by laprice** [washingtonpost/data-equitable-sharing-spending#1]
For a number of values across the dataset numeric values are formatted as numbers in some cases and strings in others. 

This seems to be an artefact of exporting from excel, since it is applied to integers greater than `999`.

So any number in the dataset that is greater than that is transformed into a display string `"1,000"` for example.

This applies to certificationid fields as well as all money fields.

From reading [this entry on msdn](https://msdn.microsoft.com/en-us/library/dd255223.aspx) it seems the solution would be to reexport the data in "compliant" rendering mode rather than "default".

This would have saved me several hours of work to wrangle the csv files into something I can bring into my analytic environment.

**Comment by stevenrich-zz** [comment]
took me long enough, but got it. thanks for flagging.
